/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PreferencesDialog.java
 *
 * Created on 20.04.2011, 15:39:26
 */

package com.spam.mctool.view.dialogs;

import com.spam.mctool.view.main.MainFrame;
import java.util.Locale;
import java.util.MissingResourceException;
import java.util.ResourceBundle;
import javax.swing.JFrame;

/**
 *
 * @author Tobias
 */
public class PreferencesDialog extends javax.swing.JDialog {
    private Selection selection;

    public Selection getSelection() {
        return selection;
    }

    /**
     * wraps a Locale for the combo box
     */
    private static class LocaleItem {
        private final Locale locale;

        public LocaleItem(Locale l) {
            this.locale = l;
        }

        @Override
        public String toString() {
            return locale.getDisplayLanguage();
        }

        public Locale getLocale() {
            return locale;
        }
    }

    private MainFrame parent;
    private boolean languageChanged = false;

    /** Creates new form PreferencesDialog */
    private PreferencesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadData();
    }

    public PreferencesDialog(MainFrame parent, boolean modal) {
        this((JFrame)parent, modal);
        this.parent = parent;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laLanguage = new javax.swing.JLabel();
        cbLanguage = new javax.swing.JComboBox();
        buCancel = new javax.swing.JButton();
        buOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("internationalization/Bundle"); // NOI18N
        setTitle(bundle.getString("PreferencesDialog.title")); // NOI18N
        setName("Form"); // NOI18N

        laLanguage.setText(bundle.getString("PreferencesDialog.laLanguage.text")); // NOI18N
        laLanguage.setName("laLanguage"); // NOI18N

        cbLanguage.setName("cbLanguage"); // NOI18N
        cbLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLanguageActionPerformed(evt);
            }
        });

        buCancel.setText(bundle.getString("PreferencesDialog.buCancel.text")); // NOI18N
        buCancel.setName("buCancel"); // NOI18N
        buCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buCancelActionPerformed(evt);
            }
        });

        buOk.setText(bundle.getString("PreferencesDialog.buOk.text")); // NOI18N
        buOk.setName("buOk"); // NOI18N
        buOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(buOk, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buCancel)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laLanguage)
                .addGap(36, 36, 36)
                .addComponent(cbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laLanguage)
                    .addComponent(cbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buCancel)
                    .addComponent(buOk))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buOkActionPerformed
        selection = Selection.APPROVE_SELECTION;
        dispose();
    }//GEN-LAST:event_buOkActionPerformed

    private void buCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buCancelActionPerformed
        selection = Selection.DISCARD_SELECTION;
        dispose();
    }//GEN-LAST:event_buCancelActionPerformed

    private void cbLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLanguageActionPerformed
        
    }//GEN-LAST:event_cbLanguageActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PreferencesDialog dialog = new PreferencesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buCancel;
    private javax.swing.JButton buOk;
    private javax.swing.JComboBox cbLanguage;
    private javax.swing.JLabel laLanguage;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        for(Locale l : Locale.getAvailableLocales()) {
            ResourceBundle bundle = ResourceBundle.getBundle("internationalization/Bundle", l);
            if(bundle.getLocale().equals(l)) {
                LocaleItem li = new LocaleItem(l);
                cbLanguage.addItem(li);
                if(Locale.getDefault().equals(l)) {
                    cbLanguage.setSelectedItem(li);
                }
            }
        }
    }

    /**
     * returns the localized name of the language selected in the combo box
     * @return
     */
    public Locale getSelectedLocale() {
        return ((LocaleItem)cbLanguage.getSelectedItem()).getLocale();
    }

}
