/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShowSenderDialog.java
 *
 * Created on Mar 3, 2011, 7:48:01 PM
 */

package com.spam.mctool.view.dialogs;

import com.spam.mctool.intermediates.SenderDataChangedEvent;
import com.spam.mctool.model.Sender;
import com.spam.mctool.model.SenderDataChangeListener;
import com.spam.mctool.view.main.MainFrame;
import java.net.Inet4Address;
import java.net.Inet6Address;
import java.net.InetAddress;
import java.net.InterfaceAddress;
import javax.swing.JFrame;

/**
 *
 * @author Tobias Schoknecht (Tobias.Schoknecht@de.ibm.com)
 */
public class ShowSenderDialog extends javax.swing.JDialog implements SenderDataChangeListener{

    private static final long serialVersionUID = 1L;
    private Sender sender;
    private MainFrame parent;

	/** Creates new form ShowSenderDialog */
    public ShowSenderDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private ShowSenderDialog(MainFrame parent, boolean modal) {
        this((JFrame)parent, modal);
        this.parent = parent;
    }

    public ShowSenderDialog(MainFrame parent, boolean modal, Sender sender) {
        this(parent, modal);
        this.sender = sender;
        loadData();
        this.jGraph.setMaxPacketRate(this.sender.getSenderConfiguredPacketRate());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        senderIDLabel = new javax.swing.JLabel();
        senderIDData = new javax.swing.JLabel();
        interfaceLabel = new javax.swing.JLabel();
        interfaceData = new javax.swing.JLabel();
        groupLabel = new javax.swing.JLabel();
        groupData = new javax.swing.JLabel();
        portLabel = new javax.swing.JLabel();
        portData = new javax.swing.JLabel();
        packetStyleLabel = new javax.swing.JLabel();
        packetStyleData = new javax.swing.JLabel();
        packetSizeLabel = new javax.swing.JLabel();
        packetSizeData = new javax.swing.JLabel();
        dataLabel = new javax.swing.JLabel();
        dataData = new javax.swing.JLabel();
        confPPSLabel = new javax.swing.JLabel();
        confPPSData = new javax.swing.JLabel();
        sentPPSLabel = new javax.swing.JLabel();
        sentPPSData = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jGraph = new JPanelGraph();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("internationalization/Bundle"); // NOI18N
        setTitle(bundle.getString("ShowSenderDialog.title")); // NOI18N
        setName("Form"); // NOI18N

        senderIDLabel.setText(bundle.getString("ShowSenderDialog.senderIDLabel.text")); // NOI18N
        senderIDLabel.setName("senderIDLabel"); // NOI18N

        senderIDData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        senderIDData.setText(bundle.getString("ShowSenderDialog.senderIDData.text")); // NOI18N
        senderIDData.setName("senderIDData"); // NOI18N

        interfaceLabel.setText(bundle.getString("ShowSenderDialog.interfaceLabel.text")); // NOI18N
        interfaceLabel.setName("interfaceLabel"); // NOI18N

        interfaceData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        interfaceData.setText(bundle.getString("ShowSenderDialog.interfaceData.text")); // NOI18N
        interfaceData.setName("interfaceData"); // NOI18N

        groupLabel.setText(bundle.getString("ShowSenderDialog.groupLabel.text")); // NOI18N
        groupLabel.setName("groupLabel"); // NOI18N

        groupData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        groupData.setText(bundle.getString("ShowSenderDialog.groupData.text")); // NOI18N
        groupData.setName("groupData"); // NOI18N

        portLabel.setText(bundle.getString("ShowSenderDialog.portLabel.text")); // NOI18N
        portLabel.setName("portLabel"); // NOI18N

        portData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        portData.setText(bundle.getString("ShowSenderDialog.portData.text")); // NOI18N
        portData.setName("portData"); // NOI18N

        packetStyleLabel.setText(bundle.getString("ShowSenderDialog.packetStyleLabel.text")); // NOI18N
        packetStyleLabel.setName("packetStyleLabel"); // NOI18N

        packetStyleData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        packetStyleData.setText(bundle.getString("ShowSenderDialog.packetStyleData.text")); // NOI18N
        packetStyleData.setName("packetStyleData"); // NOI18N

        packetSizeLabel.setText(bundle.getString("ShowSenderDialog.packetSizeLabel.text")); // NOI18N
        packetSizeLabel.setName("packetSizeLabel"); // NOI18N

        packetSizeData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        packetSizeData.setText(bundle.getString("ShowSenderDialog.packetSizeData.text")); // NOI18N
        packetSizeData.setName("packetSizeData"); // NOI18N

        dataLabel.setText(bundle.getString("ShowSenderDialog.dataLabel.text")); // NOI18N
        dataLabel.setName("dataLabel"); // NOI18N

        dataData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dataData.setText(bundle.getString("ShowSenderDialog.dataData.text")); // NOI18N
        dataData.setName("dataData"); // NOI18N

        confPPSLabel.setText(bundle.getString("ShowSenderDialog.confPPSLabel.text")); // NOI18N
        confPPSLabel.setName("confPPSLabel"); // NOI18N

        confPPSData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        confPPSData.setText(bundle.getString("ShowSenderDialog.confPPSData.text")); // NOI18N
        confPPSData.setName("confPPSData"); // NOI18N

        sentPPSLabel.setText(bundle.getString("ShowSenderDialog.sentPPSLabel.text")); // NOI18N
        sentPPSLabel.setName("sentPPSLabel"); // NOI18N

        sentPPSData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sentPPSData.setText(bundle.getString("ShowSenderDialog.sentPPSData.text")); // NOI18N
        sentPPSData.setName("sentPPSData"); // NOI18N

        closeButton.setText(bundle.getString("ShowSenderDialog.closeButton.text")); // NOI18N
        closeButton.setActionCommand(bundle.getString("ShowSenderDialog.closeButton.actionCommand")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jGraph.setBackground(new java.awt.Color(0, 0, 0));
        jGraph.setName("jGraph"); // NOI18N

        javax.swing.GroupLayout jGraphLayout = new javax.swing.GroupLayout(jGraph);
        jGraph.setLayout(jGraphLayout);
        jGraphLayout.setHorizontalGroup(
            jGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );
        jGraphLayout.setVerticalGroup(
            jGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(interfaceLabel)
                    .addComponent(groupLabel)
                    .addComponent(portLabel)
                    .addComponent(packetStyleLabel)
                    .addComponent(packetSizeLabel)
                    .addComponent(dataLabel)
                    .addComponent(confPPSLabel)
                    .addComponent(sentPPSLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(closeButton))
                    .addComponent(senderIDLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(groupData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(interfaceData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(portData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(packetStyleData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(senderIDData, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                    .addComponent(packetSizeData, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(dataData, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(confPPSData, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(sentPPSData, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jGraph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jGraph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(senderIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(interfaceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(groupLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(portLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(packetStyleLabel)
                        .addGap(18, 18, 18)
                        .addComponent(packetSizeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confPPSLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sentPPSLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(senderIDData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(interfaceData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(groupData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(portData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(packetStyleData)
                        .addGap(18, 18, 18)
                        .addComponent(packetSizeData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confPPSData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sentPPSData)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeButton)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ShowSenderDialog dialog = new ShowSenderDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void loadData() {
        this.senderIDData.setText(String.valueOf(this.sender.getSenderId()));

        for (InterfaceAddress interfaceAddress : this.sender.getNetworkInterface().getInterfaceAddresses()) {
            InetAddress address = interfaceAddress.getAddress();
            String ip = null;

            if(this.sender.getGroup() instanceof Inet4Address){
                if(address instanceof Inet4Address){
                    ip = address.getHostAddress();
                }
            }
            else if(this.sender.getGroup() instanceof Inet6Address){
                if(address instanceof Inet6Address){
                    ip = address.getHostAddress();
                }
            }

            this.interfaceData.setText(this.sender.getNetworkInterface().getDisplayName() + " - " + ip);
        }

        this.groupData.setText(this.sender.getGroup().getHostAddress());
        this.portData.setText(String.valueOf(this.sender.getPort()));
        this.packetStyleData.setText(this.sender.getpType().toString());
        this.packetSizeData.setText(String.valueOf(this.sender.getPacketSize()));
        this.dataData.setText(this.sender.getPayloadAsString());
        this.confPPSData.setText(String.valueOf(this.sender.getSenderConfiguredPacketRate()));
        this.sentPPSData.setText(String.valueOf(this.sender.getAvgPPS()));

        this.jGraph.newVal((int)this.sender.getAvgPPS());

    }
    
    public void dataChanged(SenderDataChangedEvent e) {
        loadData();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel confPPSData;
    private javax.swing.JLabel confPPSLabel;
    private javax.swing.JLabel dataData;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JLabel groupData;
    private javax.swing.JLabel groupLabel;
    private javax.swing.JLabel interfaceData;
    private javax.swing.JLabel interfaceLabel;
    private com.spam.mctool.view.dialogs.JPanelGraph jGraph;
    private javax.swing.JLabel packetSizeData;
    private javax.swing.JLabel packetSizeLabel;
    private javax.swing.JLabel packetStyleData;
    private javax.swing.JLabel packetStyleLabel;
    private javax.swing.JLabel portData;
    private javax.swing.JLabel portLabel;
    private javax.swing.JLabel senderIDData;
    private javax.swing.JLabel senderIDLabel;
    private javax.swing.JLabel sentPPSData;
    private javax.swing.JLabel sentPPSLabel;
    // End of variables declaration//GEN-END:variables

}
