/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GroupRowRenderer.java
 *
 * Created on 21.03.2011, 10:16:06
 */

package com.spam.mctool.view.main.receivertable;

import com.spam.mctool.model.ReceiverGroup;
import java.awt.Component;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JTable;

/**
 *
 * @author Tobias
 */
public class GroupRowRenderer extends javax.swing.JPanel implements javax.swing.table.TableCellRenderer {

    /** Creates new form GroupRowRenderer */
    public GroupRowRenderer() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laExpandIcon = new javax.swing.JLabel();
        laStateIcon = new javax.swing.JLabel();
        laGroupCaption = new javax.swing.JLabel();
        laGroup = new javax.swing.JLabel();
        laPortCaption = new javax.swing.JLabel();
        laPort = new javax.swing.JLabel();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        laExpandIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fold_closed.png"))); // NOI18N
        add(laExpandIcon);

        laStateIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stop_red.png"))); // NOI18N
        laStateIcon.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 2, 0, 0));
        add(laStateIcon);

        laGroupCaption.setText("Group:");
        laGroupCaption.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        add(laGroupCaption);

        laGroup.setText("225.1.1.14");
        add(laGroup);

        laPortCaption.setText("Port:");
        laPortCaption.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        add(laPortCaption);

        laPort.setText("2345");
        add(laPort);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel laExpandIcon;
    private javax.swing.JLabel laGroup;
    private javax.swing.JLabel laGroupCaption;
    private javax.swing.JLabel laPort;
    private javax.swing.JLabel laPortCaption;
    private javax.swing.JLabel laStateIcon;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JTable table;
    private int column;
    private final ImageIcon collapsed = new ImageIcon(getClass().getResource("/images/fold_closed.png"));
    private final ImageIcon expanded  = new ImageIcon(getClass().getResource("/images/fold_opened.png"));

    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        this.table = table;
        this.column = column;
        ReceiverGroupRow groupRow = (ReceiverGroupRow)value;
        ReceiverGroup group = (ReceiverGroup)groupRow.getReceiverGroup();
        if(groupRow.isExpanded()) {
            laExpandIcon.setIcon(expanded);
        } else {
            laExpandIcon.setIcon(collapsed);
        }
        laGroup.setText(group.getGroup().getHostAddress());
        laPort.setText("" + group.getPort());
        return this;
    }

    @Override
    public void setBounds(int x, int y, int w, int h) {
        super.setBounds(0, y, table.getWidth(), h);
    }

    @Override
    public void paint(Graphics g) {
        int columnWidths = 0;
        for(int i=0; i<column; i++) {
            columnWidths += table.getColumnModel().getColumn(i).getWidth();
        }
        g.translate(-columnWidths, 0);
        super.paint(g);
    }

}
