/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ActionRenderer.java
 *
 * Created on 07.03.2011, 22:40:48
 */

package com.spam.mctool.view.main;

import java.awt.Component;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Tobias
 */
public class ActionRenderer extends javax.swing.JPanel implements TableCellRenderer {

    /** Creates new form ActionRenderer */
    public ActionRenderer() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 2, 0));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/spam/mctool/view/images/stop_red.png"))); // NOI18N
        jButton1.setMargin(new java.awt.Insets(1, 1, 1, 1));
        add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/spam/mctool/view/images/preview.png"))); // NOI18N
        jButton2.setMargin(new java.awt.Insets(1, 1, 1, 1));
        add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/spam/mctool/view/images/edit.png"))); // NOI18N
        jButton3.setMargin(new java.awt.Insets(1, 1, 1, 1));
        add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/spam/mctool/view/images/delete.png"))); // NOI18N
        jButton4.setMargin(new java.awt.Insets(1, 1, 1, 1));
        add(jButton4);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables

    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        return this;
    }

}
