/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Mar 3, 2011, 4:57:17 PM
 */

package com.spam.mctool.view.main;

/**
 *
 * @author Tobias Stöckel (Tobias.Stoeckel@de.ibm.com)
 */
public class MainFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buActivate = new javax.swing.JButton();
        buDeactivate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        buReceiverDetails = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReceivers = new javax.swing.JTable();
        buReceiverRemove = new javax.swing.JButton();
        buReceiverEdit = new javax.swing.JButton();
        buReceiverNew = new javax.swing.JButton();
        laReceivers = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buSenderNew = new javax.swing.JButton();
        buSenderEdit = new javax.swing.JButton();
        buSenderRemove = new javax.swing.JButton();
        buSenderDetails = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSenders = new javax.swing.JTable();
        laSenders = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/spam/mctool/view/Bundle"); // NOI18N
        setTitle(bundle.getString("MainFrame.title")); // NOI18N

        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("com/spam/mctool/view/main/Bundle"); // NOI18N
        buActivate.setText(bundle1.getString("MainFrame.buActivate.text")); // NOI18N

        buDeactivate.setText(bundle1.getString("MainFrame.buDeactivate.text")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buReceiverDetails.setText(bundle1.getString("MainFrame.buReceiverDetails.text")); // NOI18N

        tableReceivers.setModel(new ReceiverTableModel());
        jScrollPane1.setViewportView(tableReceivers);

        buReceiverRemove.setText(bundle1.getString("MainFrame.buReceiverRemove.text")); // NOI18N

        buReceiverEdit.setText(bundle1.getString("MainFrame.buReceiverEdit.text")); // NOI18N

        buReceiverNew.setText(bundle1.getString("MainFrame.buReceiverNew.text")); // NOI18N

        laReceivers.setText(bundle1.getString("MainFrame.laReceivers.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buReceiverNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buReceiverRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buReceiverEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buReceiverDetails))
                    .addComponent(laReceivers))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laReceivers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buReceiverNew)
                    .addComponent(buReceiverRemove)
                    .addComponent(buReceiverEdit)
                    .addComponent(buReceiverDetails))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buSenderNew.setText(bundle1.getString("MainFrame.buSenderNew.text")); // NOI18N

        buSenderEdit.setText(bundle1.getString("MainFrame.buSenderEdit.text")); // NOI18N

        buSenderRemove.setText(bundle1.getString("MainFrame.buSenderRemove.text")); // NOI18N

        buSenderDetails.setText(bundle1.getString("MainFrame.buSenderDetails.text")); // NOI18N

        tableSenders.setModel(new SenderTableModel());
        tableSenders.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(tableSenders);
        tableSenders.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        laSenders.setText(bundle1.getString("MainFrame.laSenders.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buSenderNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buSenderRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buSenderEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buSenderDetails))
                    .addComponent(laSenders))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laSenders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buSenderNew)
                    .addComponent(buSenderRemove)
                    .addComponent(buSenderEdit)
                    .addComponent(buSenderDetails))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText(bundle1.getString("MainFrame.jMenu1.text")); // NOI18N

        jMenuItem1.setText(bundle1.getString("MainFrame.jMenuItem1.text")); // NOI18N
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText(bundle1.getString("MainFrame.jMenu2.text")); // NOI18N

        jMenuItem2.setText(bundle1.getString("MainFrame.jMenuItem2.text")); // NOI18N
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buActivate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buDeactivate))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buActivate)
                    .addComponent(buDeactivate))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buActivate;
    private javax.swing.JButton buDeactivate;
    private javax.swing.JButton buReceiverDetails;
    private javax.swing.JButton buReceiverEdit;
    private javax.swing.JButton buReceiverNew;
    private javax.swing.JButton buReceiverRemove;
    private javax.swing.JButton buSenderDetails;
    private javax.swing.JButton buSenderEdit;
    private javax.swing.JButton buSenderNew;
    private javax.swing.JButton buSenderRemove;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel laReceivers;
    private javax.swing.JLabel laSenders;
    private javax.swing.JTable tableReceivers;
    private javax.swing.JTable tableSenders;
    // End of variables declaration//GEN-END:variables

    public MainFrameState getSessionState() {
        MainFrameState state = new MainFrameState();
        state.setXPosition(this.getX());
        state.setYPosition(this.getY());
        state.setHeight(this.getHeight());
        state.setWidth(this.getWidth());
        state.setWindowState(this.getExtendedState());
        return state;
    }

    public void setSessionState(MainFrameState state) {
        this.setLocation(state.getXPosition(), state.getYPosition());
        this.setSize(state.getWidth(), state.getHeight());
        this.setExtendedState(state.getWindowState());
    }

}
