/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Mar 3, 2011, 4:57:17 PM
 */

package com.spam.mctool.view;

/**
 *
 * @author tobias
 */
public class MainFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buActivate = new javax.swing.JButton();
        buDeactivate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        buReceiverDetails = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReceivers = new javax.swing.JTable();
        buReceiverRemove = new javax.swing.JButton();
        buReceiverEdit = new javax.swing.JButton();
        buReceiverNew = new javax.swing.JButton();
        laReceivers = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buSenderNew = new javax.swing.JButton();
        buSenderEdit = new javax.swing.JButton();
        buSenderRemove = new javax.swing.JButton();
        buSenderDetails = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSenders = new javax.swing.JTable();
        laSenders = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/spam/mctool/view/Bundle"); // NOI18N
        setTitle(bundle.getString("MainFrame.title")); // NOI18N

        buActivate.setText(bundle.getString("MainFrame.buActivate.text")); // NOI18N

        buDeactivate.setText(bundle.getString("MainFrame.buDeactivate.text")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buReceiverDetails.setText(bundle.getString("MainFrame.buReceiverDetails.text")); // NOI18N

        tableReceivers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Group", "Port", "Packet Rate", "Lost Packets", "Interrupts", "max. Interrupt", "State"
            }
        ));
        tableReceivers.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tableReceivers);
        tableReceivers.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        buReceiverRemove.setText(bundle.getString("MainFrame.buReceiverRemove.text")); // NOI18N

        buReceiverEdit.setText(bundle.getString("MainFrame.buReceiverEdit.text")); // NOI18N

        buReceiverNew.setText(bundle.getString("MainFrame.buReceiverNew.text")); // NOI18N

        laReceivers.setText(bundle.getString("MainFrame.laReceivers.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buReceiverNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buReceiverRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buReceiverEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buReceiverDetails))
                    .addComponent(laReceivers))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laReceivers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buReceiverNew)
                    .addComponent(buReceiverRemove)
                    .addComponent(buReceiverEdit)
                    .addComponent(buReceiverDetails))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buSenderNew.setText(bundle.getString("MainFrame.buSenderNew.text")); // NOI18N

        buSenderEdit.setText(bundle.getString("MainFrame.buSenderEdit.text")); // NOI18N

        buSenderRemove.setText(bundle.getString("MainFrame.buSenderRemove.text")); // NOI18N

        buSenderDetails.setText(bundle.getString("MainFrame.buSenderDetails.text")); // NOI18N

        tableSenders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Group", "Port", "Packet Size", "TTL", "Packet Rate", "State"
            }
        ));
        tableSenders.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(tableSenders);
        tableSenders.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        laSenders.setText(bundle.getString("MainFrame.laSenders.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buSenderNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buSenderRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buSenderEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buSenderDetails))
                    .addComponent(laSenders))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laSenders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buSenderNew)
                    .addComponent(buSenderRemove)
                    .addComponent(buSenderEdit)
                    .addComponent(buSenderDetails))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buActivate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buDeactivate))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buActivate)
                    .addComponent(buDeactivate))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buActivate;
    private javax.swing.JButton buDeactivate;
    private javax.swing.JButton buReceiverDetails;
    private javax.swing.JButton buReceiverEdit;
    private javax.swing.JButton buReceiverNew;
    private javax.swing.JButton buReceiverRemove;
    private javax.swing.JButton buSenderDetails;
    private javax.swing.JButton buSenderEdit;
    private javax.swing.JButton buSenderNew;
    private javax.swing.JButton buSenderRemove;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel laReceivers;
    private javax.swing.JLabel laSenders;
    private javax.swing.JTable tableReceivers;
    private javax.swing.JTable tableSenders;
    // End of variables declaration//GEN-END:variables

}
